### ISSUE TITLE
"habitica status" fails with error

### ISSUE THREAD

**Issue by asmfreak** [philadams/habitica#48]
The error is:
```python
habitica status
Traceback (most recent call last):
  File "/usr/bin/habitica", line 13, in <module>
    habitica.cli()
  File "/usr/lib/python3.6/site-packages/habitica/core.py", line 320, in cli
    clct = content['quests'][quest_key][qt].values()[0]
TypeError: 'dict_values' object does not support indexing
```

**Comment by philadams-zz** [comment]
Hmm, thanks. Will investigate. I suspect I'm poorly handling the various item types quests can have. Will take a look.

**Comment by asmfreak** [comment]
More errors. Maybe it is a python3.6 thing?
```python
habitica status
Traceback (most recent call last):
  File "/usr/bin/habitica", line 13, in <module>
    habitica.cli()
  File "/usr/lib/python3.6/site-packages/habitica/core.py", line 335, in cli
    quest_title=str(quest_title))
  File "/usr/lib/python3.6/site-packages/habitica/core.py", line 115, in update_quest_cache
    cache.write(f)
  File "/usr/lib/python3.6/configparser.py", line 916, in write
    self._defaults.items(), d)
  File "/usr/lib/python3.6/configparser.py", line 923, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by crhbetz** [comment]
@ASMfreaK for the latter, there's a pull request already: https://github.com/philadams/habitica/pull/36
